name: climbing_analysis
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - matplotlib
  - mne
  - numpy
  - pandas
  - pip
  - pytest
  - python=3.9
  - pytorch
  - pytorch-cuda=11.8
  - pytables
  - statsmodels
  - h5py
  - scipy
  - yaml
  - pip:
    - open-ephys-python-tools
    - scikit-learn
    - spikeinterface
